// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetItemsItemsGetError, GetItemsItemsGetResponse, CreateItemItemsPostData, CreateItemItemsPostError, CreateItemItemsPostResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get Items
 */
export const getItemsItemsGet = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetItemsItemsGetResponse, GetItemsItemsGetError, ThrowOnError>({
        ...options,
        url: '/items/'
    });
};

/**
 * Create Item
 */
export const createItemItemsPost = <ThrowOnError extends boolean = false>(options: Options<CreateItemItemsPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateItemItemsPostResponse, CreateItemItemsPostError, ThrowOnError>({
        ...options,
        url: '/items/'
    });
};