// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Item = {
    name: string;
    price: number;
};

export type ResponseMessage = {
    message: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetItemsItemsGetResponse = (Array<Item>);

export type GetItemsItemsGetError = unknown;

export type CreateItemItemsPostData = {
    body: Item;
};

export type CreateItemItemsPostResponse = (ResponseMessage);

export type CreateItemItemsPostError = (HTTPValidationError);